# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LgxuYHzaZtPBUlHJDl2l0XSQNd9I6gMx
"""

import numpy as np
import pandas as pd
from math import sqrt
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

df = pd.read_csv('kc_house_data.csv')

df['date'] = pd.to_datetime(df['date'], format='%Y%m%dT%H%M%S')
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day_of_week'] = df['date'].dt.dayofweek

X = df.drop(['price', 'date'], axis=1)
y = df['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

knn = KNeighborsRegressor(n_neighbors=5)


knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
rmse = sqrt(sqrt(mse))
mae = mean_absolute_error(y_test, y_pred)
print("Number of neighbors:", knn.n_neighbors)
print("Test set predictions:", y_pred)
print("Mean Squared Error:", mse)
print("RMSE test score",rmse)